<?php
  $time = microtime();
  $time = explode(' ', $time);
  $time = $time[1] + $time[0];
  $finish = $time;
  $total_time = round(($finish - $start), 4);
?>
<div id="foot">
<p>
Generated by <a href="http://log1cms.sourceforge.net" target="_blank">Log1 CMS</a> in: <?php echo $total_time ?> seconds |
Your IP: <?php echo myFunctions::giveIP(); ?>
</p>
</div>